$pdf_mode = 1;
$out_dir = 'build';
$aux_dir = 'build';
$out2_dir = '.';
@out2_exts = ('pdf');

$pdflatex = 'pdflatex -shell-escape -interaction=nonstopmode -file-line-error -synctex=1 %O %S';

$clean_ext .= ' nav snm vrb synctex.gz';
